// Template for local development. Copy this file to config.js (gitignored) and fill in
// your own Supabase project's values (Project Settings -> API in the Supabase dashboard).
// In production this file is generated by .github/workflows/deploy.yml from GitHub
// Actions repo secrets — never edited or committed there either.
window.__CONFIG__ = {
  SUPABASE_URL: 'https://YOUR-PROJECT-REF.supabase.co',
  SUPABASE_ANON_KEY: 'YOUR-ANON-KEY'
};
